@c Copyright (C)  2013 Benjamin K. Johannsen
@c Permission is granted to copy, distribute and/or modify
@c this document under the terms of the GNU Free
@c Documentation License, Version 1.3 or any later version
@c published by the Free Software Foundation; with no
@c Invariant Sections, no Front-Cover Texts, and no
@c Back-Cover Texts.  A copy of the license is included in
@c the section entitled ``GNU Free Documentation License''.

The graphs are produced in subdirectories that are named to correspond
to the numbering in the manuscript.  Instructions for producing each
graph follows.  It is important that the working directory of Matlab
or Octave be the directory in which the graphing files are located,
e.g. @code{/path/to/cmrfiles/figure2}.

@menu
* Figure 1::
* Figure 2::
* Figure 3::
* Figure 4::
* Figure 5::
* Figure 7::
* Figure 8::
@end menu

@node Figure 1
@section Figure 1
In the directory @code{figure1} is a file named @code{cmr.mod}.  To
generate Figure 1, all you need to do is run dynare with this file.
That is,
@example
>> dynare cmr
@end example
@noindent

@node Figure 2
@section Figure 2
In the directory @code{figure2} is a file named @code{cmr.mod}.
This code can be used to generate impulse responses from the model shown
in Figure 2.  You have to run dynare twice.  On the first run, set the
Taylor rule inflation parameter to 1.5 by setting taylor1p5 = 1.  There
is a line near the beginning of the file that may be modified to reflect
this setting.  It should look like
@example
@@# define taylor1p5 = 1
@end example
@noindent
After making sure that this is the case, run dynare
@example
>> dynare cmr
@end example
@noindent
In addition to the files generated by Dynare, the code will produce
a file named @code{results_taylor1p5.mat} that will be used on
the next run of dynare.  After running Dynare the first time,
change taylor1p5 to be zero.  That is, in the @code{cmr.mod}
file, make sure
@example
@@# define taylor1p5 = 0
@end example
@noindent
Run dynare again,
@example
>> dynare cmr
@end example
@noindent
and the graph will be produced and appear in a separate window.

@c @node Figure 4
@c @section Figure 4
@c In the directory @code{figure4} is a file named @code{cmr.mod}.
@c This file can be used to create Figure 4.  You will need to run
@c Dynare 3 times, which slight modifications to @code{cmr.mod}
@c each time.
@c First, run the code after making sure that the following lines
@c exist in @code{cmr.mod}
@c @example
@c @@# define sticky_prices = 0
@c @@# define sticky_wages = 0
@c @@# define sigma_in_taylor_rule = 0
@c @end example
@c @noindent
@c After making sure that this is the case, run dynare
@c @example
@c >> dynare cmr
@c @end example
@c @noindent
@c This will run the code with the baseline Taylor rule and with flexible
@c wages and prices. In addition to the normal files produced by dynare,
@c the code will save the output in a file named @code{flex_price.mat}.
@c Next, run the code with
@c @example
@c @@# define sticky_prices = 1
@c @@# define sticky_wages = 1
@c @@# define sigma_in_taylor_rule = 1
@c @end example
@c @noindent
@c After making sure that this is the case, run dynare
@c @example
@c >> dynare cmr
@c @end example
@c @noindent
@c This will run the code with sticky wages and prices, as well as the risk
@c shock in the Taylor rule.  In addition to the normal files produced by dynare,
@c the code will save the output in a file named @code{sigma_taylor.mat}.
@c Finally, run the code with
@c @example
@c @@# define sticky_prices = 1
@c @@# define sticky_wages = 1
@c @@# define sigma_in_taylor_rule = 0
@c @end example
@c @noindent
@c These are the benchmark values.  
@c After making sure that this is the case, run dynare
@c @example
@c >> dynare cmr
@c @end example
@c @noindent
@c This run generates the graph.

@node Figure 3
@section Figure 3
In the directory @code{figure3} are files named @code{cmr.mod},
@code{correlate.m}, @code{difftrans.m}, @code{hpfast.m}, @code{se.m}
@code{corr_.m},	@code{cross_corr.m}, @code{do_plot.m}, and @code{pltt.m}.  
This code can be used to generate correlograms shown
in Figure 3.  You have to run dynare twice.  On the first run, turn off
the non-risk shocks by setting stopshock to 1.  There
is a line near the beginning of the file that may be modified to reflect
this setting.  It should look like
@example
@@# define stopshock = 1
@end example
@noindent
After making sure that this is the case, run dynare
@example
>> dynare cmr
@end example
@noindent
In addition to the files generated by Dynare, the code will produce
several mat files that will be used on
the next run of dynare.  After running Dynare the first time,
change stopshock to be 0.  That is, in the @code{cmr.mod}
file, make sure
@example
@@# define stopshock = 0
@end example
@noindent
Run dynare again,
@example
>> dynare cmr
@end example
@noindent
and the graph will be produced and appear in a separate window.

@node Figure 4
@section Figure 4
In the directory @code{figure4} is a file named @code{cmr.mod}.  To
generate Figure 4, all you need to do is run dynare with this file.
That is,
@example
>> dynare cmr
@end example
@noindent

@node Figure 5
@section Figure 5
In the directory @code{figure5} are files named @code{cmr.mod},
@code{cmr_mode.mat}, and @code{cmr_mode_cee.mat}.
This code can be used to generate Figure 5.  The @code{.mat} file is required by the
@code{estimation} command in Dynare, which is used to recover the 
smoothed variables without actually doing the estimation.
You have to run dynare twice.  On the first run, you restrict the
model to be a version of the model in Christiano, Evans, and Eichenbaum
by setting the macro variable cee to 1.  There
is a line near the beginning of the file that may be modified to reflect
this setting.  It should look like
@example
@@# define cee = 1
@end example
@noindent
After making sure that this is the case, run dynare
@example
>> dynare cmr
@end example
@noindent
In addition to the files generated by Dynare, the code will produce
a mat file that will be used on
the next run of dynare.  After running Dynare the first time,
change cee to be 0.  That is, in the @code{cmr.mod}
file, make sure
@example
@@# define cee = 0
@end example
@noindent
Run dynare again,
@example
>> dynare cmr
@end example
@noindent
and the graph will be produced and appear in a separate window.

@node Figure 7
@section Figure 7
In the directory @code{figure7} are files named @code{cmr.mod}, @code{hpfast.m}
and @code{cmr_mode.mat}.  The @code{.mat} file is required by the
@code{estimation} command in Dynare, which is used to recover the 
smoothed variables without actually doing the estimation.  To
generate Figure 7, all you need to do is run dynare with the
@code{cmr.mod} file.
That is,
@example
>> dynare cmr
@end example
@noindent


@node Figure 8
@section Figure 8
In the directory @code{figure8} is a file named @code{cmr.mod} and a file
named @code{cmr_mode.mat}.  The @code{.mat} file is required by the
@code{estimation} command in Dynare, which is used to recover the 
smoothed variables without actually doing the estimation.  To
generate Figure 8, all you need to do is run dynare with the
@code{cmr.mod} file.
That is,
@example
>> dynare cmr
@end example
@noindent
